version: '3.3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - nashseverewx-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${FORWARD_WEB_PORT:-8081}:8080'
    environment:
      REDIS_ADDR: '${REDIS_ADDR}'
    depends_on:
      - redis
    networks:
      - nashseverewx-network
networks:
  nashseverewx-network:
    driver: bridge